using System.Threading;
using System.Threading.Tasks;
using MediatR;
using EnterpriseCraft.Template.Modules.Customers.Domain;
using EnterpriseCraft.Template.Shared.Persistence;

namespace EnterpriseCraft.Template.Modules.Customers.Features.CreateCustomer;

public class Handler : IRequestHandler<Command, Response>
{
    private readonly AppDbContext _db;

    public Handler(AppDbContext db)
    {
        _db = db;
    }

    public async Task<Response> Handle(Command request, CancellationToken cancellationToken)
    {
        var customer = new Customer
        {
            // Id is generated by base AuditableEntity
            Name = request.Name,
            Email = request.Email,
            Phone = request.Phone,
            IsDeleted = false
        };

        _db.Set<Customer>().Add(customer);
        await _db.SaveChangesAsync(cancellationToken);

        return new Response(customer.Id);
    }
}